kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap1
data:
  URL: example.com
  SUBDOMAIN: sample
  FQDN: sample.example.com



---
kind: Pod
apiVersion: v1
metadata:
  name: sample1
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["/bin/sh", "-c"]
    args: ["ls ; ls -al"]
    envFrom:
    - configMapRef:
        name: configmap1


---
