kind: ConfigMap
apiVersion: v1
metadata:
  name: configMap1
data:
  URL: google.com
  SOURCE: google



---
kind: Pod
apiVersion: v1
metadata:
  name: sample1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      configMapRef:
        - name: configMap1
  - name: centos
    image: centos:7
    command: ["sleep", "100000"]




