#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: configmap1
#data:
#  URL: example.com
#  SUBDOMAIN: sample
#  FQDN: sample.example.com
#
#
#
#---
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#  - name: centos
#    image: centos:7
#    command: ["/bin/sh", "-c"]
#    args: ["sleep 10 ; sleep 100"]
#    envFrom:
#    - configMapRef:
#        name: configmap1

---

apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - name: nginx
    image: nginx
    resources :
      requests :
        memory : "128Mi"
        cpu : "50m"
      limits :
        memory : "256Mi"
        cpu : "100m"
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 60
    readinessProbe :
      exec :
        command :
        - cat
        - /tmp/healthy
      initialDelaySeconds : 5
      periodSeconds : 5
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5


