#deployment not supports parameters
#we have to write same code for each app those many times.
#so we came with HELM CHARTS.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .value.appName }}
  labels:
    app: guestbook
    tier: {{ .value.appName }}-deploy
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: {{ .value.appName }}-deploy
  template:
    metadata:
      labels:
        tier: {{ .value.appName }}-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
