#deployment not supports parameters
#we have to write same code for each app those many times.
#so we came with HELM CHARTS.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-1
  labels:
    app: guestbook
    tier: frontend-deploy-1
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend-deploy-1
  template:
    metadata:
      labels:
        tier: frontend-deploy-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
