#deployment not supports parameters
#we have to write same code for each app those many times.
#so we came with HELM CHARTS.

#helm install <some name> <location of helm directory> -f <name of app>
# helm install name ./helm -f cart.yml

# ./helm containd deploymentset, configmao etc. cart.yaml is used to send variables



apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: guestbook
    tier: {{ .Values.appName }}-deploy
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: {{ .Values.appName }}-deploy
  template:
    metadata:
      labels:
        tier: {{ .Values.appName }}-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
