#FROM uses for sourcing image and create our image. after run ( docker build . ) command to create image
#ADD use for add a file into image ( ADD file_name folder_name )

#FROM nginx
#ADD index.html /usr/share/nginx/html/index.html

#RUN use for run a command while building an image. i.e,

ADD   centos:7
RUN   yum install nginx -y

