#FROM         uses for sourcing image and create our image. after run ( docker build . ) command to create image
#ADD          use for add a file into image ( ADD file_name folder_name )
#RUN          use for run a command while building an image.
#ENTRYPOINT   use to run a command while launching a container
#EXPOSE       use to open a port by container

# epel is third party repository. in this repo we have nginx, so we installing epel before nginx


FROM       centos:7
RUN        yum install epel-release -y
RUN        yum install nginx -y
ADD        index.html /usr/share/nginx/html/index.html
EXPOSE     80
ENTRYPOINT ["nginx", "-g", "daemon off;"]


