#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#  - name: nginx
#    image: nginx
#
#---
#
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample2
#spec:
#  containers:
#  - name: nginx
#    image: nginx
#  - name: mongodb
#    image: mongo
#


kind: Pod
apiVersion: v1
metadata:
  name: sample3
spec:
  containers:
  - name: nginx
    image: nginx
  - name: centos
    image: centos:7
    command : ["sleep", "10000"]

---
kind: Pod
apiVersion: v1
metadata:
  name: sample4
spec:
  containers:
  - name: nginx
    image: nginx
    resources :
      requests :
        cpu: "50m"
        memory: "128Mi"
      limits :
        cpu : "100m"
        memory : "256Mi"

---

kind: Pod
apiVersion: v1
metadata:
  name: sample5
spec:
  containers:
  - name: centos
    image: centos:7
    command : ["sleep", "10000"]
    env:
    - name: URL
      value: example.com

# this env used for send env variable. but in reality trher are more env vars for that
#we use   "ConfigMap"     option
#1cpu = 1000 milli core, request are min, limits are max values


---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap1
data:
  URL: example.com
  SUBDOMAIN: sample
  FQDN: sample.example.com
---
kind: Pod
apiVersion: v1
metadata:
  name: sample6
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep", "10000"]
    envFrom:
    - configMapRef:
        name: configmap1

---
# echo -n admin1 | base64
# echo -n admin1 | base64
# run above command to get decode value of user and passwd
#args and commands are same
---
kind: Secret
apiVersion: v1
metadata:
  name: secret1
data:
  dbUsername: YWRtaW4x
  dbPassword: YWRtaW4xMjM0

---
kind: Pod
apiVersion: v1
metadata:
  name: sample7
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep"]
    args: ["10000"]
    envFrom:
    - secretRef:
        name: secret1

---

apiVersion: v1
kind: Pod
metadata:
  name: sample8
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    readinessProbe :
      exec :
        command :
        - cat
        - /tmp/healthy
      initialDelaySeconds : 5
      periodSeconds : 5
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5


