#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#  - name: nginx
#    image: nginx
#
#---
#
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample2
#spec:
#  containers:
#  - name: nginx
#    image: nginx
#  - name: mongodb
#    image: mongo
#


kind: Pod
apiVersion: v1
metadata:
  name: sample3
spec:
  containers:
  - name: nginx
    image: nginx
  - name: centos
    image: centos:7
    command : ["sleep", "10000"]

---

kind: Pod
apiVersion: v1
metadata:
  name: sample5
spec:
  containers:
  - name: centos
    image: centos:7
    command : ["sleep", "10000"]
    env:
    - name: URL
      value: example.com

# this env used for send env variable. but in reality trher are more env vars for that
#we use   "ConfigMap"     option

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap1
data:
  URL: example.com
  SUBDOMAIN: some.name
  FQDN: example.domain.name

---

kind: Pod
apiVersion: v1
metadata:
  name: sample6
spec:
  containers:
  - name: centos
    image: centos:7
    command : ["sleep", "10000"]
    envFrom:
    - configMapRef:
        name: configMap1
